apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination: 
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    repoURL: git@github.com:venkata22a/k8stest.git
    targetRevision: HEAD
    chart: nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
